add setup scripts & fix bugs

diff --git a/{{cookiecutter.project_name}}/scripts/local/backup b/{{cookiecutter.project_name}}/scripts/local/backup
--- a/{{cookiecutter.project_name}}/scripts/local/backup
+++ b/{{cookiecutter.project_name}}/scripts/local/backup
@@ -8,4 +8,9 @@ fi
 
 container_id=$(docker ps -aqf "name=^{{cookiecutter.project_name}}_local_postgres$")
 docker exec -it "$container_id" pg_dump -U {{cookiecutter.project_name}} > data/local_backup.sql
-echo "Backup successful"
+if [[ $? -eq 0 ]]
+then
+echo "Local Backup successful"
+else
+echo "Local Backup Failed"
+fi
